# Generated by Django 5.1.2 on 2024-11-20 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_settingsmonitor_timesreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmonitor',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='settingsmonitor',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='settingsmonitor',
            name='timesReview',
        ),
        migrations.AddField(
            model_name='settingsmonitor',
            name='interval_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settingsmonitor',
            name='interval_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settingsmonitor',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
