# Generated by Django 5.1.2 on 2024-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_permissions_user_permissions_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_user',
            field=models.CharField(max_length=128),
        ),
    ]
