# Generated by Django 5.1.2 on 2024-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_user',
        ),
    ]
