# Generated by Django 5.1.2 on 2024-12-02 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCheckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('service_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('response_code', models.CharField(max_length=10)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Last Check Status',
                'verbose_name_plural': 'Last Check Statuses',
                'ordering': ['-checked_at'],
            },
        ),
    ]
